name: Python tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 1 * *"

jobs:
  unit-tests:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Don't clone history
          submodules: true # Update submodules
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Dependencies
        run: |
          sudo apt install cmake curl git unzip zip ninja-build g++ gcc make gfortran autoconf libtool python3-dev autoconf-archive pkg-config liblapack-dev libblas-dev
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install pytest matplotlib
      - name: Build the simcem wheel
        env:
          COINHSL_DOWNLOAD_URL: ${{ secrets.COINHSL_DOWNLOAD_URL }}
        run: |
          source .venv/bin/activate
          python -m pip wheel . --wheel-dir dist/
      - name: Install simcem wheel
        run: |
          source .venv/bin/activate
          python -m pip install dist/simcem-*.whl
      - name: Test simcem
        run: |
          source .venv/bin/activate
          pytest tests

